name: KnightmaresReign
version: Beta 0.0.1
main: xyz.knightmaresreign.KnightmaresReign
api-version: 1.19
depend: [ ProtocolLib ]

commands:
  getbonk:
    description: Gives the player a test item.
  getbook:
    description: BOOK